server:
 port: 8989
spring:
 application:
  name: CODE-SERVICE
 config:
  import: optional:configserver:http://localhost:8111 
eureka:
 instance:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/ 
management:
 endpoints: 
  web.exposure:
   include: "*"    

